services:
    token07.serversboard.controller:
        class: token07\serversboard\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@request'
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '%token07.serversboard.tables.serversboard%'
    token07.serversboard.listener:
        class: token07\serversboard\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '%token07.serversboard.tables.serversboard%'
            - @?phpbb.collapsiblecategories.operator
        tags:
            - { name: event.listener }
    token07.serversboard.cron.task.update_serversboard:
        class: token07\serversboard\cron\task\update_serversboard
        arguments:
            - '@config'
            - '@dbal.conn'
            - '%token07.serversboard.tables.serversboard%'
        calls:
            - [set_name, [cron.task.update_serversboard]]
        tags:
            - { name: cron.task }
    token07.serversboard.admin_controller:
        class: token07\serversboard\controller\admin_controller
        arguments:
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@log'
            - '@token07.serversboard.cron.task.update_serversboard'
            - '%token07.serversboard.tables.serversboard%'
parameters:
    token07.serversboard.tables.serversboard: %core.table_prefix%serversboard
